### ISSUE TITLE
Insert Maps & Location in footers

### ISSUE THREAD

**Issue by amanojha33** [IIITL-DeV/ResearchGroup#1]
http://web.mit.edu/chemistry/jamison/Group/Group%20Index.html 

Refer above website and insert same maps and location info of college with contacts at bottom of HOME (index.html). Show me then copy to other pages.

**Comment by amanojha33** [comment]
d

**Comment by Cronus1007** [comment]
@amanojha33 Sir This has already been implemented.
![Screenshot from 2021-04-03 18-10-33](https://user-images.githubusercontent.com/56436023/113478676-ec4f4780-94a7-11eb-96e2-d33d2daf3de1.png)

**Comment by Cronus1007** [comment]
This issue has been implemented with commit https://github.com/IIITL-DeV/ResearchGroup/commit/2fbece941e4024a44698b530edeba6abfe9ba163
