### ISSUE TITLE
Remove white box in index.html before description

### ISSUE THREAD

**Issue by amanojha33** [IIITL-DeV/ResearchGroup#22]
![Screen Shot 2021-04-17 at 10 35 57 AM](https://user-images.githubusercontent.com/52046367/115102497-dbeba200-9f68-11eb-91d9-f74a286d03de.png)

**Comment by Cronus1007** [comment]
@amanojha33 
Is this looking nice?
![Screenshot from 2021-04-19 13-12-10](https://user-images.githubusercontent.com/56436023/115199516-eb0d5400-a110-11eb-8b6f-63ef97829567.png)

**Comment by amanojha33** [comment]
That will work. Ok
