### ISSUE TITLE
Insert space in all section(3 pages) of research as shown below.

### ISSUE THREAD

**Issue by amanojha33** [IIITL-DeV/ResearchGroup#5]
![Screen Shot 2021-04-05 at 1 51 42 PM](https://user-images.githubusercontent.com/52046367/113553953-28081f80-9616-11eb-8d6b-ff8320b31b9a.png)

Local copy working, but github pages not producing space.

**Comment by Cronus1007** [comment]
@amanojha33 Sir local copy also not working.
![Uploading Screenshot from 2021-04-05 14-18-12.png…]()

**Comment by Cronus1007** [comment]
@amanojha33 This issue is also occuring on local.Take a git pull.

**Comment by Cronus1007** [comment]
![Screenshot from 2021-04-05 14-31-53](https://user-images.githubusercontent.com/56436023/113557479-b3d07a80-961b-11eb-9a61-4404f156f2b9.png)
@amanojha33 Sir is this all right.
